-- CREATING CITIES TABLE
CREATE TABLE IF NOT EXISTS mayors (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    cities_id INT UNSIGNED,
    PRIMARY KEY(id),
    UNIQUE KEY (cities_id),
    FOREIGN KEY(cities_id) REFERENCES cities (id)
);