-- CREATING COMPANIES TABLE
CREATE TABLE IF NOT EXISTS companies (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    cnpj INT UNSIGNED NOT NULL,
    PRIMARY KEY(id),
    UNIQUE KEY (cnpj)
);